Repository Yeasir0032/Discord-Clone, pull requests merged in 2024-06, with the labels that each got.

#86 Create LEARN.md
  LEARN.md
Labels: level1, gssoc

#69 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: good first issue, gssoc

#76 added register form
  components/home-layouts/Register.tsx
Labels: level2, gssoc
