Repository Yeasir0032/Discord-Clone, pull requests merged in 2024-05, with the labels that each got.

#12 Update README.md
  README.md
Labels: documentation, Level 1

#49 Update Contributing.md
  Contributing.md
Labels: documentation, level1, gssoc

#44 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: good first issue, level1, gssoc

#33 #18 Creating a explore page for servers
  app/(setup)/page.tsx
  app/api/servers/getAllServers/route.ts
Labels: enhancement, level3, gssoc

#72 feat: added Server exploration button
  components/navigation/explorer-action.tsx
  components/navigation/navigation-sideBar.tsx
Labels: good first issue, level2, gssoc
